import { PhraseBankItem } from "@/lib/types";

const seed = (cefr: PhraseBankItem["cefr"], phrases: string[]) => phrases.map((phrase, index) => ({ id: `${cefr.toLowerCase()}-${index + 1}`, cefr, phrase }));

export const phraseBank: PhraseBankItem[] = [
  ...seed("A1", [
    "a few",
    "a good idea",
    "all right",
    "at home",
    "by bus",
    "every day",
    "for lunch",
    "for me",
    "go home",
    "good morning",
    "good night",
    "have breakfast",
    "have lunch",
    "have dinner",
    "in bed",
    "in class",
    "in the morning",
    "in the afternoon",
    "in the evening",
    "listen to",
    "look at",
    "of course",
    "on the weekend",
    "play soccer",
    "ride a bike",
    "see you soon",
    "sit down",
    "stand up",
    "take a shower",
    "thank you very much",
    "this morning",
    "wait for",
    "wake up",
    "work hard",
    "would like to"
  ]),
  ...seed("A2", [
    "a couple of",
    "all the time",
    "as soon as",
    "be interested in",
    "be good at",
    "be late for",
    "be worried about",
    "come back",
    "come from",
    "do my best",
    "each other",
    "for the first time",
    "get better",
    "get home",
    "get ready",
    "go out",
    "grow up",
    "have a cold",
    "have a great time",
    "have fun",
    "help with",
    "in front of",
    "keep in touch",
    "look for",
    "make a mistake",
    "make friends",
    "on time",
    "pick up",
    "put on",
    "run out of",
    "spend time doing",
    "stay up late",
    "take care of",
    "talk about",
    "the next day",
    "think about",
    "try on",
    "turn off",
    "turn on",
    "work together"
  ]),
  ...seed("B1", [
    "a bit more",
    "a lot of pressure",
    "all over the world",
    "as a result",
    "at least",
    "be able to",
    "be likely to",
    "break down",
    "carry on",
    "come up with",
    "deal with",
    "depend on",
    "figure out",
    "find out",
    "get used to",
    "give up",
    "in charge of",
    "in common",
    "keep doing",
    "make progress",
    "on my own",
    "pay attention to",
    "put together",
    "rather than",
    "set a goal",
    "sort out",
    "take part in",
    "take place",
    "the rest of",
    "work out"
  ]),
  ...seed("B2", [
    "a wide range of",
    "as far as I know",
    "at risk",
    "be aware of",
    "be based on",
    "be capable of",
    "be involved in",
    "by the time",
    "come across",
    "cut down on",
    "draw attention to",
    "from my point of view",
    "have an impact on",
    "in addition to",
    "in contrast",
    "in terms of",
    "make the most of",
    "play a role in",
    "point out",
    "put pressure on",
    "raise awareness of",
    "take advantage of",
    "the majority of",
    "to a certain extent",
    "under pressure",
    "with regard to",
    "work toward",
    "be responsible for",
    "keep track of",
    "make sense of"
  ]),
  ...seed("C1", [
    "a great deal of",
    "as opposed to",
    "at the expense of",
    "be subject to",
    "bring about",
    "call into question",
    "come to terms with",
    "draw a distinction between",
    "for the sake of",
    "in light of",
    "in the long run",
    "it goes without saying",
    "make a compelling case",
    "on the grounds that",
    "on the verge of",
    "place emphasis on",
    "run the risk of",
    "serve as a reminder",
    "shed light on",
    "strike a balance",
    "take into account",
    "the extent to which",
    "throw into sharp relief",
    "with the exception of",
    "without a doubt"
  ])
];

export const cefrRank: Record<string, number> = {
  A1: 1,
  A2: 2,
  B1: 3,
  B2: 4,
  C1: 5,
  C2: 6
};

